Ignore new warnings reported by clang 14
clang 14.0.6 reports (for x86-64):

    include/uapi/linux/hyperv.h:361:2: error: field  within 'struct
    hv_kvp_exchg_msg_value' is less aligned than
    'union hv_kvp_exchg_msg_value::(anonymous at
    include/uapi/linux/hyperv.h:361:2)' and is usually due to 'struct
    hv_kvp_exchg_msg_value' being packed, which can lead to unaligned
    accesses [-Werror,-Wunaligned-access]
            union {
            ^
    1 error generated.