Ignore -Wused-but-marked-unused when building with clang
Since 5.7-rc7:

      HOSTCC  scripts/kconfig/parser.tab.o
    scripts/kconfig/parser.tab.c:1057:54: error: 'yysymbol_name' was
    marked unused but was used [-Werror,-Wused-but-marked-unused]
                 yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));
                                                         ^